# Generated by Django 4.0.3 on 2022-06-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='YourName',
            field=models.TextField(default='jddd'),
        ),
    ]
