# Generated by Django 4.0.3 on 2022-07-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0004_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
