# Generated by Django 4.0.3 on 2022-07-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=80)),
                ('custom_number', models.CharField(max_length=11)),
                ('food_name', models.CharField(max_length=80)),
                ('add_ons', models.CharField(max_length=80)),
                ('number_order', models.CharField(max_length=2)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('custom_add', models.TextField(blank=True)),
                ('custom_message', models.TextField(blank=True)),
            ],
        ),
    ]
