# Generated by Django 4.0.3 on 2022-07-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0007_customers_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='order',
            name='custom_add',
        ),
        migrations.RemoveField(
            model_name='order',
            name='custom_message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='custom_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_order',
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
