# Generated by Django 4.0.3 on 2022-07-03 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0008_customer_product_delete_customers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
