# Generated by Django 4.0.3 on 2022-07-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0012_size_order_customer_order_product_order_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='size',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='size',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=200, null=True),
        ),
    ]
