# Generated by Django 4.0.3 on 2022-07-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0013_rename_size_tag_rename_size_order_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='gtsys.tag'),
        ),
    ]
