# Generated by Django 4.0.3 on 2022-07-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0014_remove_order_tags_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ManyToManyField(to='gtsys.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='avail',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tub', 'Tub'), ('Cup', 'Cup'), ('Soya Milk', 'Soya Milk')], max_length=200, null=True),
        ),
    ]
