# Generated by Django 4.0.3 on 2022-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0016_remove_order_size_order_adds_delete_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adds',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tub', 'Tub'), ('Cup', 'Cup'), ('Soya Milk', 'Soya Milk'), ('Add Ons', 'Add Ons')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Addons',
        ),
    ]
