# Generated by Django 4.0.3 on 2022-07-05 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0018_feedback_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=200, null=True)),
                ('adds_name', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtsys.cart'),
        ),
    ]
