# Generated by Django 4.0.3 on 2022-07-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtsys', '0019_cart_rename_email_customer_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='main_name',
            new_name='product_name',
        ),
    ]
